### ISSUE TITLE
plt.figtext function isn't working

### ISSUE THREAD

**Issue by kcho5820** [PacktPublishing/Hands-On-Predictive-Analytics-with-Python#1]
Hi, it seems the plt.figtext isn't working properly in my case - showing only the graph but not the text. Did I miss anything?

Below is the result:

`n [6]: desc_num_feature('price')
C:\Users\kathy\Anaconda3\lib\site-packages\pandas\core\ops.py:1649: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)
Traceback (most recent call last):

  File "<ipython-input-6-d7282557f788>", line 1, in <module>
    desc_num_feature('price')

  File "<ipython-input-5-c90c3ffcf3ce>", line 5, in desc_num_feature
    plt.figtext(1,0.15, diamonds[feature_name].describe().round(2), size=17)

  File "C:\Users\kathy\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 726, in figtext
    return gcf().text(x, y, s, *args, **kwargs)

  File "C:\Users\kathy\Anaconda3\lib\site-packages\matplotlib\figure.py", line 1799, in text
    text = Text(x=x, y=y, text=s)

  File "C:\Users\kathy\Anaconda3\lib\site-packages\matplotlib\text.py", line 163, in __init__
    self.set_text(text)

  File "C:\Users\kathy\Anaconda3\lib\site-packages\matplotlib\text.py", line 1191, in set_text
    if s != self._text:

  File "C:\Users\kathy\Anaconda3\lib\site-packages\pandas\core\generic.py", line 1478, in __nonzero__
    .format(self.__class__.__name__))

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().`

Your help would be much appreciated. Thank you!

**Comment by ArtemAleksieiev** [comment]
It can work with  .to_string() method
 plt.figtext(1, 0.15, diamonds[feature_name].describe().round(2).to_string(), size=17)

**Comment by DanielKomlaElijah** [comment]
> It can work with .to_string() method
> plt.figtext(1, 0.15, diamonds[feature_name].describe().round(2).to_string(), size=17)

Worked. Thanks

**Comment by quantcompany** [comment]
The solution provided by @ArtemAleksieiev  works. But the bug has been (finally) fixed.
